#Count the number of restaurants in each city.

select city, count(restaurant_id) as Total_Restaurants
from zomato_restaurants
group by citY
Order by Total_restaurants desc;

#Find the top 5 cities with the highest number of orders.

select r.city, count(o.order_id) as Total_orders
from zomato_orders o
inner join zomato_restaurants r on o.restaurant_id=r.restaurant_id
group by r.city
order by Total_orders desc
limit 5;


#Calculate the total revenue generated by each restaurant.

Select r.restaurant_name, sum(o.total_cost) as Total_Revenue
from zomato_orders o
inner join zomato_restaurants r on o.restaurant_id=r.restaurant_id
group by r.restaurant_name
order by Total_revenue desc;

#Find the average order amount for each city.
select r.city, avg(o.total_cost) as Average_order_amount
from zomato_orders o
inner join zomato_restaurants r on o.restaurant_id=r.restaurant_id
group by r.city
order by Average_order_amount desc;

#Identify the top 5 restaurants with the highest total sales.
Select r.restaurant_name, sum(o.total_cost) as Total_sales
from zomato_orders o
inner join zomato_restaurants r on o.restaurant_id=r.restaurant_id
group by r.restaurant_name
order by Total_sales desc
Limit 5;

#Data Joins
select r.restaurant_name, o.order_id, o.customer_id, o.order_date, o.order_time, o.delivery_time,o.total_cost, o.item_count,o.payment_method, o.customer_rating
from zomato_orders o
inner join zomato_restaurants r on o.restaurant_id=r.restaurant_id;


